---

- name: gather facts
  setup:

- name: Sort hosts by distribution
  group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"
  changed_when: false

- name: Guess bookkeeper_service_user - set ansible_user as default
  set_fact:
    bookkeeper_service_user: "{{ ansible_user }}"
  when: bookkeeper_service_user is not defined

- name: Guess bookkeeper_service_user - use become_user under root
  set_fact:
    bookkeeper_service_user: "{{ ansible_become_user }}"
  when: bookkeeper_service_user == 'root' and ansible_become_user is defined

- name: Set deploy dir if not presented
  set_fact: bookkeeper_home="/home/{{ bookkeeper_service_user }}"
  when: bookkeeper_home is not defined

- include_tasks: tasks.yml
