---

- name: gather facts
  setup:

- name: Sort hosts by distribution
  group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_version }}"
  changed_when: false

- name: Guess deploy_user - set ansible_user as default
  set_fact:
    deploy_user: "{{ ansible_user }}"
  when: deploy_user is not defined

- name: Guess deploy_user - use become_user under root
  set_fact:
    deploy_user: "{{ ansible_become_user }}"
  when: deploy_user == 'root' and ansible_become_user is defined

- name: Set deploy dir if not presented
  set_fact: deploy_dir="/home/{{ deploy_user }}/deploy"
  when: deploy_dir is not defined

- include_tasks: tasks.yml
