---

# start zookeeper cluster

- hosts: zookeeper
  tags:
    - zookeeper
  tasks:
    - name: Start zookeeper by systemd
      systemd: name=zookeeper.service state=started
      become: true
      when: process_supervision == 'systemd'

    - name: Wait for zookeeper up
      shell: echo ruok | nc localhost 2181 
      register: task_result
      until: task_result.stdout == "imok"
      retries: 30
      delay: 2
      ignore_errors: yes
