---

# start zookeeper cluster

- hosts: zookeeper
  tags:
    - zookeeper
  tasks:
    - name: Start zookeeper by systemd
      systemd: name=zookeeper.service state=started
      become: true
      when: process_supervision == 'systemd'

    - name: Wait for zookeeper up
      uri:
        url: "http://localhost:{{ zk_admin_port }}/commands/ruok"
        status_code: 200
      register: wait_result
      until: wait_result.status == 200
      retries: 60
      delay: 1
      ignore_errors: no
