---

# stop zookeeper cluster

- hosts: zookeeper
  tags:
    - zookeeper
  tasks:
    - name: Stop zookeeper by systemd
      systemd: name=zookeeper.service state=stopped
      become: true
      when: process_supervision == 'systemd'

    - name: Wait for zookeeper down
      uri:
        url: "http://localhost:{{ zk_admin_port }}/commands/ruok"
        status_code: -1
      register: wait_result
      until: wait_result.status == -1
      retries: 60
      delay: 1
      ignore_errors: yes
