---

# distro specific tasks

- name: Debian/Ubuntu - install python
  raw: sudo apt-get -y install python
  when:
    - "'Ubuntu' in distro or 'Debian' in distro"
    - "not has_python"

- name: Redhat/CentOS - install python
  raw: sudo yum -y install python
  when:
    - "'CentOS' in distro"
    - "not has_python"
