---

- name: Disk space check - Fail task when disk is full
  raw: df -h . | tail -n1
  register: disk_space_st
  failed_when: " '100%' in disk_space_st.stdout "
  changed_when: false

- name: Get facts
  setup:

- name: Preflight check - Guess bookkeeper_service_user - set ansible_user as default
  set_fact:
    bookkeeper_service_user: "{{ ansible_user }}"
  when: bookkeeper_service_user is not defined

- name: Preflight check - Guess bookkeeper_service_user - use become_user under root
  set_fact:
    bookkeeper_service_user: "{{ ansible_become_user }}"
  when: bookkeeper_service_user == 'root' and ansible_become_user is defined and ansible_become_user

- name: Preflight check - Set bookkeeper_home dir if not presented
  set_fact: bookkeeper_home="/home/{{ bookkeeper_service_user }}"
  when: bookkeeper_home is not defined

- name: Preflight check - Check bookkeeper service user
  fail:
    msg: Never deploy under root user
  when: bookkeeper_service_user=='root'

- name: Preflight check - Get umask
  shell: umask
  register: umask
  changed_when: False

- name: Preflight check - Get Hard Max FD limit
  shell: ulimit -H -n
  register: ulimit
  changed_when: False

- name: Preflight check - Does the system have a standard umask?
  fail:
    msg: 'The umask of the system ({{ umask.stdout.strip() }}) prevents successful installation. We suggest a standard umask such as 0022.'
  when: umask.stdout.strip()[-2:] not in ('00', '02', '20', '22')

- name: Preflight check - ulimit -n
  fail:
    msg: 'The default max number of file descriptors is too low {{ ulimit.stdout }} should be {{ min_open_fds }}'
  when: ulimit.stdout|int < min_open_fds|int

- name: Preflight check - Get bookkeeper home permissions
  stat: path={{ bookkeeper_home }}
  register: vl_st

- name: Preflight check - Does bookkeeper home dir have appropriate permissions?
  fail:
    msg: 'The permissions on {{ bookkeeper_home }} ({{ vl_st.stat.mode }}) prevent successful installation. {{ bookkeeper_home }} must be world-readable.'
  when: vl_st.stat.roth is defined and not vl_st.stat.roth

- name: Preflight check - Check swap
  debug:
    msg: Swap is on, for best performance, turn swap off
  when: "ansible_memory_mb.swap.total is defined and 0 < ansible_memory_mb.swap.total|int"

- name: Environment check - BookKeeper Home
  stat: path={{ bookkeeper_home }} get_md5=false get_checksum=false
  register: bookkeeper_home_st

- name: Environment check - Supervise
  stat: path={{ bookkeeper_home }}/bin/supervise get_md5=false get_checksum=false
  register: supervise_st
  when:
    - process_supervision == 'supervise'
    - bookkeeper_home_st.stat.isdir is defined
    - bookkeeper_home_st.stat.isdir

- name: Config skip variables (default)
  set_fact:
    skip_create_bookkeeper_home: false
    skip_supervise: false

- name: Config skip variables
  set_fact:
    skip_create_bookkeeper_home: true
  when:
    - bookkeeper_home_st is defined
    - bookkeeper_home_st.stat is defined
    - bookkeeper_home_st.stat.writeable is defined
    - bookkeeper_home_st.stat.writeable
    - bookkeeper_home_st.stat.readable
    - bookkeeper_home_st.stat.isdir

- name: Config skip variables
  set_fact:
    skip_supervise: true
  when:
    - process_supervision == 'supervise'
    - supervise_st is defined
    - supervise_st.stat is defined
    - supervise_st.stat.executable is defined
    - supervise_st.stat.executable
