---

- name: Create alertmanager directories
  file: path="{{ item }}" state=directory mode=0755
  with_items:
  - "{{ alertmanager_log_dir }}"
  - "{{ alertmanager_data_dir }}"

- name: Deploy alertmanager binary
  copy: src="{{ resources_dir }}/bin/alertmanager" dest="{{ bookkeeper_home }}/bin/" mode=0755

- name: Create run script
  template:
    src: "{{ item }}_{{ role_name }}_binary.sh.j2"
    dest: "{{ bookkeeper_home }}/scripts/{{ item }}_{{ role_name }}.sh"
    mode: "0755"
    backup: yes
  with_items:
    - run
  vars:
    role_status_dir: status/{{ role_name }}

- include_tasks: "{{ process_supervision }}_deployment.yml"
